{
	vars,
	inputs,
	...
}: {
	home-manager = {
		extraSpecialArgs = {inherit inputs vars;};
		users.${vars.user.name} = {...}: {
			programs.dank-material-shell = {
				enable = true;
				# Core features
				enableSystemMonitoring = true; # System monitoring widgets (dgop)
				enableVPN = true; # VPN management widget
				enableDynamicTheming = true; # Wallpaper-based theming (matugen)
				enableAudioWavelength = true; # Audio visualizer (cava)
				enableCalendarEvents = true; # Calendar integration (khal)
				enableClipboardPaste = true;

				systemd = {
					enable = true; # Systemd service for auto-start
					restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
				};
				# niri = {
				# enableKeybinds = false;
				# enableSpawn = false;
				# includes = {
				#   enable = true; # Enable config includes hack. Enabled by default.

				#   override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
				#   originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
				#   filesToInclude = [
				# Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
				#     "alttab" # Please note that niri will throw an error if any of these files are missing.
				#     "binds"
				#     "colors"
				#     "layout"
				#     "outputs"
				#     "wpblur"
				#     "imports"
				#   ];
				# };
				# };
			};
		};
	};
}
